"""initial DB

Revision ID: b72a695ac403
Revises: 
Create Date: 2018-09-06 23:40:03.196300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b72a695ac403'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_lists',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('business', sa.String(length=255), nullable=True),
    sa.Column('listing_bourse', sa.String(length=60), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_lists')
    # ### end Alembic commands ###
