"""initial DB

Revision ID: d04f0788b6b3
Revises: 
Create Date: 2018-09-09 23:04:19.391138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd04f0788b6b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_lists',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('ticker_symbol', sa.Text(), nullable=True),
    sa.Column('uid', sa.Text(), nullable=True),
    sa.Column('business', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.Text(), nullable=True),
    sa.Column('contact_website', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.Text(), nullable=True),
    sa.Column('listing_bourse', sa.Text(), nullable=True),
    sa.Column('address_full_en', sa.Text(), nullable=True),
    sa.Column('address_full', sa.Text(), nullable=True),
    sa.Column('address_city_district', sa.Text(), nullable=True),
    sa.Column('address_street', sa.Text(), nullable=True),
    sa.Column('address_province', sa.Text(), nullable=True),
    sa.Column('address_country', sa.Text(), nullable=True),
    sa.Column('business_summary', sa.Text(), nullable=True),
    sa.Column('business_summary_en', sa.Text(), nullable=True),
    sa.Column('market_cap', sa.Text(), nullable=True),
    sa.Column('financial_summary', sa.Text(), nullable=True),
    sa.Column('business_registration', sa.Text(), nullable=True),
    sa.Column('auditing_company', sa.Text(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_lists')
    # ### end Alembic commands ###
